import { Categorias } from "../enums/categorias";
import { Juego } from "./juego";

export interface JuegoPreguntados  extends Juego{

}


export interface Pregunta {
  id: number;
  categoria: Categorias;
  pregunta: string;
  respuestas: Array<{respuesta: string, correcta: boolean}>;
  jugada: boolean;
}




const Trivias: Pregunta[] = [
  {
    id: 0,
    categoria: Categorias.Historia,
    pregunta: "¿En qué año comenzó la Revolución Francesa?",
    respuestas: [
      { respuesta: "1789", correcta: true },
      { respuesta: "1804", correcta: false },
      { respuesta: "1812", correcta: false },
      { respuesta: "1850", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 1,
    categoria: Categorias.Historia,
    pregunta: "¿Quién fue el líder de la Revolución Rusa en 1917?",
    respuestas: [
      { respuesta: "Joseph Stalin", correcta: false },
      { respuesta: "Mikhail Gorbachev", correcta: false },
      { respuesta: "Nikita Khrushchev", correcta: false },
      { respuesta: "Vladimir Lenin", correcta: true },
    ],
    jugada: false,
  },
  {
    id: 2,
    categoria: Categorias.Historia,
    pregunta: "¿En qué año se firmó la Declaración de Independencia de los Estados Unidos?",
    respuestas: [
      { respuesta: "1865", correcta: false },
      { respuesta: "1789", correcta: false },
      { respuesta: "1776", correcta: true },
      { respuesta: "1804", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 3,
    categoria: Categorias.Historia,
    pregunta: "¿Cuál fue el emperador romano conocido como 'El Grande'?",
    respuestas: [
      { respuesta: "Calígula", correcta: false },
      { respuesta: "Augusto", correcta: true },
      { respuesta: "Trajano", correcta: false },
      { respuesta: "Nerón", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 4,
    categoria: Categorias.Historia,
    pregunta: "¿En qué año se firmó el Tratado de Versalles que puso fin a la Primera Guerra Mundial?",
    respuestas: [
      { respuesta: "1939", correcta: false },
      { respuesta: "1914", correcta: false },
      { respuesta: "1919", correcta: true },
      { respuesta: "1923", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 5,
    categoria: Categorias.Historia,
    pregunta: "¿Cuál fue la antigua civilización que construyó las pirámides de Giza?",
    respuestas: [
      { respuesta: "Maya", correcta: false },
      { respuesta: "Roma", correcta: false },
      { respuesta: "Egipto", correcta: true },
      { respuesta: "Grecia", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 6,
    categoria: Categorias.Historia,
    pregunta: "¿En qué año se produjo la caída del Muro de Berlín?",
    respuestas: [
      { respuesta: "1975", correcta: false },
      { respuesta: "1989", correcta: true },
      { respuesta: "1991", correcta: false },
      { respuesta: "1994", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 7,
    categoria: Categorias.Historia,
    pregunta: "¿En qué año comenzó la Segunda Guerra Mundial?",
    respuestas: [
      { respuesta: "1945", correcta: false },
      { respuesta: "1941", correcta: false },
      { respuesta: "1939", correcta: true },
      { respuesta: "1950", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 8,
    categoria: Categorias.Historia,
    pregunta: "¿Cuál fue el nombre del líder político y militar francés durante la Segunda Guerra Mundial?",
    respuestas: [
      { respuesta: "Adolf Hitler", correcta: false },
      { respuesta: "Winston Churchill", correcta: false },
      { respuesta: "Charles de Gaulle", correcta: true },
      { respuesta: "Benito Mussolini", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 9,
    categoria: Categorias.Historia,
    pregunta: "¿Cuál fue el resultado de la Revolución Rusa de 1917?",
    respuestas: [
      { respuesta: "Independencia de Ucrania", correcta: false },
      { respuesta: "Derrocamiento del régimen zarista y establecimiento del gobierno comunista", correcta: true },
      { respuesta: "Anexión de Crimea por parte de Rusia", correcta: false },
      { respuesta: "Reinstauración de la monarquía", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 10,
    categoria: Categorias.Deporte,
    pregunta: "¿En qué año se celebró la primera Copa Mundial de Fútbol?",
    respuestas: [
      { respuesta: "1970", correcta: false },
      { respuesta: "1950", correcta: false },
      { respuesta: "1930", correcta: true },
      { respuesta: "1990", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 11,
    categoria: Categorias.Deporte,
    pregunta: "¿Cuál es el país de origen del tenista Roger Federer?",
    respuestas: [
      { respuesta: "España", correcta: false },
      { respuesta: "Suiza", correcta: true },
      { respuesta: "Australia", correcta: false },
      { respuesta: "Estados Unidos", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 12,
    categoria: Categorias.Deporte,
    pregunta: "¿Cuál es el deporte más practicado en la India?",
    respuestas: [
      { respuesta: "Tenis", correcta: false },
      { respuesta: "Fútbol", correcta: false },
      { respuesta: "Hockey", correcta: false },
      { respuesta: "Críquet", correcta: true },
    ],
    jugada: false,
  },
  {
    id: 13,
    categoria: Categorias.Deporte,
    pregunta: "¿Quién es el máximo goleador en la historia de la selección brasileña de fútbol? (2020)",
    respuestas: [
      { respuesta: "Ronaldo", correcta: false },
      { respuesta: "Pelé", correcta: true },
      { respuesta: "Neymar", correcta: false },
      { respuesta: "Ronaldinho", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 14,
    categoria: Categorias.Deporte,
    pregunta: "¿Cuál es el único país que ha ganado las tres competiciones de la UEFA (Eurocopa, Copa Mundial y Liga de Naciones de la UEFA)?",
    respuestas: [
      { respuesta: "España", correcta: false },
      { respuesta: "Francia", correcta: false },
      { respuesta: "Alemania", correcta: true },
      { respuesta: "Italia", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 15,
    categoria: Categorias.Deporte,
    pregunta: "¿En qué deporte se utiliza una cancha llamada 'frontón'?",
    respuestas: [
      { respuesta: "Pelota vasca", correcta: true },
      { respuesta: "Bádminton", correcta: false },
      { respuesta: "Polo", correcta: false },
      { respuesta: "Críquet", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 16,
    categoria: Categorias.Deporte,
    pregunta: "¿Cuál es el equipo de fútbol con más Champions League ganadas?",
    respuestas: [
      { respuesta: "FC Barcelona", correcta: false },
      { respuesta: "Real Madrid", correcta: true },
      { respuesta: "Bayern Munich", correcta: false },
      { respuesta: "Manchester United", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 17,
    categoria: Categorias.Deporte,
    pregunta: "¿Qué nadador estadounidense ha ganado el mayor número de medallas olímpicas de la historia?",
    respuestas: [
      { respuesta: "Ryan Lochte", correcta: false },
      { respuesta: "Mark Spitz", correcta: false },
      { respuesta: "Michael Phelps", correcta: true },
      { respuesta: "Ian Thorpe", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 18,
    categoria: Categorias.Deporte,
    pregunta: "¿Cuál es el deporte nacional de Canadá?",
    respuestas: [
      { respuesta: "Fútbol", correcta: false },
      { respuesta: "Béisbol", correcta: false },
      { respuesta: "Hockey sobre hielo", correcta: true },
      { respuesta: "Baloncesto", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 19,
    categoria: Categorias.Deporte,
    pregunta: "¿Cuál es el nombre del famoso torneo de tenis que se juega en Wimbledon?",
    respuestas: [
      { respuesta: "Roland Garros", correcta: false },
      { respuesta: "US Open", correcta: false },
      { respuesta: "The Championships", correcta: true },
      { respuesta: "Australian Open", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 20,
    categoria: Categorias.Ciencia,
    pregunta: "¿Cuál es la unidad básica de la estructura de los seres vivos?",
    respuestas: [
      { respuesta: "Célula", correcta: true },
      { respuesta: "Átomo", correcta: false },
      { respuesta: "Molécula", correcta: false },
      { respuesta: "Organela", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 21,
    categoria: Categorias.Ciencia,
    pregunta: "¿Cuál es el planeta más grande del sistema solar?",
    respuestas: [
      { respuesta: "Saturno", correcta: false },
      { respuesta: "Neptuno", correcta: false },
      { respuesta: "Júpiter", correcta: true },
      { respuesta: "Urano", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 22,
    categoria: Categorias.Ciencia,
    pregunta: "¿Qué es la fotosíntesis?",
    respuestas: [
      { respuesta: "Proceso de formación de células nuevas", correcta: false },
      { respuesta: "Reacción química que libera energía", correcta: false },
      { respuesta: "Proceso mediante el cual las plantas convierten la luz solar en energía", correcta: true },
      { respuesta: "Proceso de descomposición de materia orgánica", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 23,
    categoria: Categorias.Ciencia,
    pregunta: "¿Cuál es la fórmula química del agua?",
    respuestas: [
      { respuesta: "H2O2", correcta: false },
      { respuesta: "H2O", correcta: true },
      { respuesta: "NaCl", correcta: false },
      { respuesta: "CH4", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 24,
    categoria: Categorias.Ciencia,
    pregunta: "¿Qué científico formuló la teoría de la relatividad?",
    respuestas: [
      { respuesta: "Isaac Newton", correcta: false },
      { respuesta: "Stephen Hawking", correcta: false },
      { respuesta: "Albert Einstein", correcta: true },
      { respuesta: "Marie Curie", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 25,
    categoria: Categorias.Ciencia,
    pregunta: "¿Cuál es la velocidad de la luz en el vacío?",
    respuestas: [
      { respuesta: "156,288,455 metros por segundo", correcta: false },
      { respuesta: "523,125,866 metros por segundo", correcta: false },
      { respuesta: "299,792,458 metros por segundo", correcta: true },
      { respuesta: "200,000,000 metros por segundo", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 26,
    categoria: Categorias.Ciencia,
    pregunta: "¿Cuál es el órgano encargado de bombear la sangre en el cuerpo humano?",
    respuestas: [
      { respuesta: "Corazón", correcta: true },
      { respuesta: "Cerebro", correcta: false },
      { respuesta: "Hígado", correcta: false },
      { respuesta: "Pulmón", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 27,
    categoria: Categorias.Ciencia,
    pregunta: "¿Cuál es la teoría que explica el origen del universo?",
    respuestas: [
      { respuesta: "Teoría del Caos", correcta: false },
      { respuesta: "Big Bang", correcta: true },
      { respuesta: "Teoría de la Evolución", correcta: false },
      { respuesta: "Teoría de la Relatividad", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 28,
    categoria: Categorias.Ciencia,
    pregunta: "¿Cuál es el elemento químico más abundante en el universo?",
    respuestas: [
      { respuesta: "Carbono", correcta: false },
      { respuesta: "Oxígeno", correcta: false },
      { respuesta: "Hidrógeno", correcta: true },
      { respuesta: "Helio", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 29,
    categoria: Categorias.Ciencia,
    pregunta: "¿Cuál es la rama de la biología que se ocupa del estudio de los organismos y su clasificación?",
    respuestas: [
      { respuesta: "Anatomía", correcta: false },
      { respuesta: "Genética", correcta: false },
      { respuesta: "Taxonomía", correcta: true },
      { respuesta: "Ecología", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 30,
    categoria: Categorias.Arte,
    pregunta: "¿Quién pintó la famosa obra 'La Gioconda'?",
    respuestas: [
      { respuesta: "Pablo Picasso", correcta: false },
      { respuesta: "Vincent van Gogh", correcta: false },
      { respuesta: "Leonardo da Vinci", correcta: true },
      { respuesta: "Michelangelo", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 31,
    categoria: Categorias.Arte,
    pregunta: "¿En qué ciudad se encuentra la famosa Ópera de Sídney?",
    respuestas: [
      { respuesta: "Nueva York", correcta: false },
      { respuesta: "Sídney", correcta: true },
      { respuesta: "París", correcta: false },
      { respuesta: "Roma", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 32,
    categoria: Categorias.Arte,
    pregunta: "¿Quién escribió la obra de teatro 'Romeo y Julieta'?",
    respuestas: [
      { respuesta: "Miguel de Cervantes", correcta: false },
      { respuesta: "Federico García Lorca", correcta: false },
      { respuesta: "William Shakespeare", correcta: true },
      { respuesta: "Oscar Wilde", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 33,
    categoria: Categorias.Arte,
    pregunta: "¿Quién compuso la famosa obra musical 'La Novena Sinfonía'?",
    respuestas: [
      { respuesta: "Wolfgang Amadeus Mozart", correcta: false },
      { respuesta: "Johann Sebastian Bach", correcta: false },
      { respuesta: "Ludwig van Beethoven", correcta: true },
      { respuesta: "Frédéric Chopin", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 34,
    categoria: Categorias.Arte,
    pregunta: "¿Qué pintor es conocido por su obra 'Los girasoles'?",
    respuestas: [
      { respuesta: "Salvador Dalí", correcta: false },
      { respuesta: "Pablo Picasso", correcta: false },
      { respuesta: "Vincent van Gogh", correcta: true },
      { respuesta: "Claude Monet", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 35,
    categoria: Categorias.Arte,
    pregunta: "¿Cuál es la escultura más famosa de Miguel Ángel?",
    respuestas: [
      { respuesta: "La Pietà", correcta: true },
      { respuesta: "El David", correcta: false },
      { respuesta: "El Pensador", correcta: false },
      { respuesta: "La Venus de Milo", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 36,
    categoria: Categorias.Arte,
    pregunta: "¿Qué famoso pintor fue conocido por su estilo 'cubista'?",
    respuestas: [
      { respuesta: "Leonardo da Vinci", correcta: false },
      { respuesta: "Vincent van Gogh", correcta: false },
      { respuesta: "Pablo Picasso", correcta: true },
      { respuesta: "Salvador Dalí", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 37,
    categoria: Categorias.Arte,
    pregunta: "¿Quién es el autor de la obra de teatro 'Hamlet'?",
    respuestas: [
      { respuesta: "Anton Chejov", correcta: false },
      { respuesta: "Tennessee Williams", correcta: false },
      { respuesta: "William Shakespeare", correcta: true },
      { respuesta: "Arthur Miller", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 38,
    categoria: Categorias.Arte,
    pregunta: "¿Cuál es la técnica de pintura que utiliza ceras de colores?",
    respuestas: [
      { respuesta: "Acuarela", correcta: false },
      { respuesta: "Óleo", correcta: false },
      { respuesta: "Crayón", correcta: true },
      { respuesta: "Pastel", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 39,
    categoria: Categorias.Arte,
    pregunta: "¿Quién es el autor del famoso cuadro 'La noche estrellada'?",
    respuestas: [
      { respuesta: "Claude Monet", correcta: false },
      { respuesta: "Vincent van Gogh", correcta: true },
      { respuesta: "Pablo Picasso", correcta: false },
      { respuesta: "Salvador Dalí", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 40,
    categoria: Categorias.Entretenimiento,
    pregunta: "¿Quién interpreta a Iron Man en el Universo Cinematográfico de Marvel?",
    respuestas: [
      { respuesta: "Chris Evans", correcta: false },
      { respuesta: "Robert Downey Jr.", correcta: true },
      { respuesta: "Chris Hemsworth", correcta: false },
      { respuesta: "Mark Ruffalo", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 41,
    categoria: Categorias.Entretenimiento,
    pregunta: "¿En qué película de Quentin Tarantino aparece el personaje de 'Mia Wallace'?",
    respuestas: [
      { respuesta: "Pulp Fiction", correcta: true },
      { respuesta: "Reservoir Dogs", correcta: false },
      { respuesta: "Kill Bill", correcta: false },
      { respuesta: "Django sin Cadenas", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 42,
    categoria: Categorias.Entretenimiento,
    pregunta: "¿Cuál es el nombre del niño que es el personaje principal de la saga de peliculas en el mundo magico?",
    respuestas: [
      { respuesta: "Ron Weasley", correcta: false },
      { respuesta: "Hermione Granger", correcta: false },
      { respuesta: "Harry Potter", correcta: true },
      { respuesta: "Severus Snape", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 43,
    categoria: Categorias.Entretenimiento,
    pregunta: "¿En qué año se estrenó la película 'El Padrino'?",
    respuestas: [
      { respuesta: "1968", correcta: false },
      { respuesta: "1972", correcta: true },
      { respuesta: "1980", correcta: false },
      { respuesta: "1990", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 44,
    categoria: Categorias.Entretenimiento,
    pregunta: "¿Cuál es el nombre del villano principal en la saga de películas 'Star Wars'?",
    respuestas: [
      { respuesta: "Luke Skywalker", correcta: false },
      { respuesta: "Darth Vader", correcta: true },
      { respuesta: "Obi-Wan Kenobi", correcta: false },
      { respuesta: "Han Solo", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 45,
    categoria: Categorias.Entretenimiento,
    pregunta: "¿Quién interpreta a Captain Jack Sparrow en la saga de películas 'Piratas del Caribe'?",
    respuestas: [
      { respuesta: "Orlando Bloom", correcta: false },
      { respuesta: "Johnny Depp", correcta: true },
      { respuesta: "Geoffrey Rush", correcta: false },
      { respuesta: "Javier Bardem", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 46,
    categoria: Categorias.Entretenimiento,
    pregunta: "¿Cuál es el nombre del protagonista en la serie de televisión 'Breaking Bad'?",
    respuestas: [
      { respuesta: "Jesse Pinkman", correcta: false },
      { respuesta: "Saul Goodman", correcta: false },
      { respuesta: "Walter White", correcta: true },
      { respuesta: "Skyler White", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 47,
    categoria: Categorias.Entretenimiento,
    pregunta: "¿Cuál es el nombre del actor que interpreta a Spider-Man en las películas del Universo Cinematográfico de Marvel?",
    respuestas: [
      { respuesta: "Andrew Garfield", correcta: false },
      { respuesta: "Tobey Maguire", correcta: false },
      { respuesta: "Tom Holland", correcta: true },
      { respuesta: "Jake Gyllenhaal", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 48,
    categoria: Categorias.Entretenimiento,
    pregunta: "¿Cuál es el nombre del personaje principal en la serie de televisión 'Game of Thrones'?",
    respuestas: [
      { respuesta: "Arya Stark", correcta: false },
      { respuesta: "Jon Snow", correcta: true },
      { respuesta: "Daenerys Targaryen", correcta: false },
      { respuesta: "Cersei Lannister", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 49,
    categoria: Categorias.Entretenimiento,
    pregunta: "¿En qué año se estrenó la película 'Titanic'?",
    respuestas: [
      { respuesta: "1995", correcta: false },
      { respuesta: "1997", correcta: true },
      { respuesta: "1999", correcta: false },
      { respuesta: "2001", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 50,
    categoria: Categorias.Geografia,
    pregunta: "¿Cuál es el río más largo del mundo?",
    respuestas: [
      { respuesta: "Nilo", correcta: false },
      { respuesta: "Misisipi", correcta: false },
      { respuesta: "Amazonas", correcta: true },
      { respuesta: "Yangtsé", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 51,
    categoria: Categorias.Geografia,
    pregunta: "¿En qué continente se encuentra el país de Australia?",
    respuestas: [
      { respuesta: "América", correcta: false },
      { respuesta: "Asia", correcta: false },
      { respuesta: "Oceanía", correcta: true },
      { respuesta: "Europa", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 52,
    categoria: Categorias.Geografia,
    pregunta: "¿Cuál es el país más grande del mundo por superficie?",
    respuestas: [
      { respuesta: "Rusia", correcta: true },
      { respuesta: "Canadá", correcta: false },
      { respuesta: "China", correcta: false },
      { respuesta: "Estados Unidos", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 53,
    categoria: Categorias.Geografia,
    pregunta: "¿Cuál es la capital de España?",
    respuestas: [
      { respuesta: "Barcelona", correcta: false },
      { respuesta: "Sevilla", correcta: false },
      { respuesta: "Madrid", correcta: true },
      { respuesta: "Valencia", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 54,
    categoria: Categorias.Geografia,
    pregunta: "¿En qué país se encuentra la Gran Barrera de Coral?",
    respuestas: [
      { respuesta: "México", correcta: false },
      { respuesta: "Australia", correcta: true },
      { respuesta: "Brasil", correcta: false },
      { respuesta: "Tailandia", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 55,
    categoria: Categorias.Geografia,
    pregunta: "¿Cuál es el océano más grande del mundo?",
    respuestas: [
      { respuesta: "Océano Atlántico", correcta: false },
      { respuesta: "Océano Índico", correcta: false },
      { respuesta: "Océano Pacífico", correcta: true },
      { respuesta: "Océano Ártico", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 56,
    categoria: Categorias.Geografia,
    pregunta: "¿En qué continente se encuentra el desierto del Sahara?",
    respuestas: [
      { respuesta: "Asia", correcta: false },
      { respuesta: "África", correcta: true },
      { respuesta: "América", correcta: false },
      { respuesta: "Europa", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 57,
    categoria: Categorias.Geografia,
    pregunta: "¿Cuál es el país más pequeño del mundo?",
    respuestas: [
      { respuesta: "Mónaco", correcta: false },
      { respuesta: "Nauru", correcta: false },
      { respuesta: "Ciudad del Vaticano", correcta: true },
      { respuesta: "Tuvalu", correcta: false },
    ],
    jugada: false,
  },
  {
    id: 58,
    categoria: Categorias.Geografia,
    pregunta: "¿Cuál es el país más poblado del mundo?",
    respuestas: [
      { respuesta: "India", correcta: false },
      { respuesta: "Estados Unidos", correcta: false },
      { respuesta: "Indonesia", correcta: false },
      { respuesta: "China", correcta: true },
    ],
    jugada: false,
  },
  {
    id: 59,
    categoria: Categorias.Geografia,
    pregunta: "¿En qué continente se encuentra el monte Kilimanjaro?",
    respuestas: [
      { respuesta: "África", correcta: true },
      { respuesta: "Asia", correcta: false },
      { respuesta: "América", correcta: false },
      { respuesta: "Europa", correcta: false },
    ],
    jugada: false,
  },
];


export default Trivias;
//Historia, Deporte, Ciencia, Arte, Entretenimeinto y Geografia
